package com.sainti.blackcard.mhttp.constant;


public class TurnClassUrl {
    public final static String fuli_list = "http://api.qing-hei.com/index.php/Index/Api?type=welfare";
    public final static String hudong_list = "http://api.qing-hei.com/index.php/Index/Api?type=messagea";
    public final static String shanping = "http://api.qing-hei.com/index.php/Index/Api?type=guide";
    public final static String yanzhengma = "http://api.qing-hei.com/index.php/Index/Api?type=get_code";
    public final static String yanzhengmalogin = "http://api.qing-hei.com/index.php/Index/Api?type=codelogin";
    public final static String guanjia = "http://api.qing-hei.com/index.php/Index/Api?type=butler_home";
    public final static String mima = "http://api.qing-hei.com/index.php/Index/Api?type=get_newpass";
    public final static String zhiYe = "http://api.qing-hei.com/index.php/Index/Api?type=zhiye_update";
    public final static String jianjie = "http://api.qing-hei.com/index.php/Index/Api?type=intro_update";
    public final static String shangchuan = "http://api.qing-hei.com/index.php/Index/Api?type=publish_find";
    public final static String huatilist = "http://api.qing-hei.com/index.php/Index/Api?type=topic";
    public final static String setYinSi = "http://api.qing-hei.com/index.php/Index/Api?type=privacy";
    public final static String getHobby = "http://api.qing-hei.com/index.php/Index/Api?type=getHobby";
    public final static String sendHobby = "http://api.qing-hei.com/index.php/Index/Api?type=hobby_update";
    public final static String sendLocation = "http://api.qing-hei.com/index.php/Index/Api?type=location_update";
    public final static String getbangding = "http://api.qing-hei.com/index.php/Index/Api?type=friends_bindinfo";
    public final static String setBangding = "http://api.qing-hei.com/index.php/Index/Api?type=friends_bind";
    public final static String getMoney = "http://api.qing-hei.com/index.php/Index/Api?type=advance_add";
    public final static String pingan = "http://api.qing-hei.com/index.php/Index/Api?type=pingan";
    public final static String guanggao = "http://api.qing-hei.com/index.php/Index/Api?type=appadpush";
    public final static String airorder_detail = "http://api.qing-hei.com/index.php/Index/Api?type=airorder_detail";
    public final static String airorder = "http://api.qing-hei.com/index.php/Index/Api?type=airorder";
    public final static String getdizhi = "http://api.qing-hei.com/index.php/Index/Api?type=user_address";
    public final static String deletedizhi = "http://api.qing-hei.com/index.php/Index/Api?type=del_address";
    public final static String adddizhi = "http://api.qing-hei.com/index.php/Index/Api?type=add_address";
    public final static String updatadizhi = "http://api.qing-hei.com/index.php/Index/Api?type=edit_address";
    public final static String getyouhuijuan = "http://api.qing-hei.com/index.php/Index/Api?type=wel_couponlist";
    public final static String haowuxiadan = "http://api.qing-hei.com/index.php/Index/Api?type=welorder_add";
    public final static String haowuxiangqing = "http://api.qing-hei.com/index.php/Index/Api?type=wel_detail";
    public final static String mine_data = "http://api.qing-hei.com/index.php/Index/Api?type=mine_data";
    public final static String update = "http://api.qing-hei.com/index.php/Index/Api?type=version_update";
    public final static String newshare = "http://api.qing-hei.com/index.php/Index/Api?type=newshare";
    /*new*/
    public final static String privilege = "http://api.qing-hei.com/index.php/Index/Api?type=blackcard.v4";
    public final static String fulifenlei = "http://api.qing-hei.com/index.php/Index/Api?type=welfare_type";
    public final static String coffeeleft = "http://api.qing-hei.com/index.php/Index/Api?type=coffee";
    public final static String adree = "http://api.qing-hei.com/index.php/Index/Api?type=coffee_address";
    public final static String addAdree = "http://api.qing-hei.com/index.php/Index/Api?type=edit_coffee_address";
    public final static String orderInfo = "http://api.qing-hei.com/index.php/Index/Api?type=coffee_order";
    public final static String moreTequan = " http://api.qing-hei.com/index.php/Index/Api?type=more_privilege";
    public final static String alipay_apporder = " http://api.qing-hei.com/mobile.php/Index/new_alipay_apporder";
    public final static String welcart_add = " http://api.qing-hei.com/index.php/Index/Api?type=welcart_add";
    public final static String welcart = " http://api.qing-hei.com/index.php/Index/Api?type=welcart";
    public final static String welcart_order = " http://api.qing-hei.com/index.php/Index/Api?type=welcart_order";
    public final static String apporder = " http://api.qing-hei.com/mobile.php/Index/apporder";
    public final static String newfindv4 = "http://api.qing-hei.com/index.php/Index/Api?type=newfind.v4";
    public final static String praise = "http://api.qing-hei.com/index.php/Index/Api?type=praise";
    public final static String isfollow = "http://api.qing-hei.com/index.php/Index/Api?type=isfollow";
    public final static String follow = "http://api.qing-hei.com/index.php/Index/Api?type=follow";
    public final static String topic_detail = "http://api.qing-hei.com/index.php/Index/Api?type=topic_detail";
    public final static String find_detail = "http://api.qing-hei.com/index.php/Index/Api?type=find_detail";
    public final static String publish_comment = "http://api.qing-hei.com/index.php/Index/Api?type=publish_comment";
    public final static String delete_find = "http://api.qing-hei.com/index.php/Index/Api?type=delete_find";
    public final static String my_findlist = "http://api.qing-hei.com/index.php/Index/Api?type=my_findlist";
    public final static String user_findlist = "http://api.qing-hei.com/index.php/Index/Api?type=user_findlist";
    public final static String fansList = "http://api.qing-hei.com/index.php/Index/Api?type=fans";
    public final static String unread = "http://api.qing-hei.com/index.php/Index/Api?type=unread";
    public final static String pingan_pay = "http://api.qing-hei.com/index.php/Index/Api?type=pingan_pay";
    public final static String login_bindinfo = "http://www.qing-hei.com/index.php/Index/Api?type=login_bindinfo";
    public static final String reg_info = "http://www.qing-hei.com/index.php/Index/Api?type=reg_info";
    public static final String login = "http://api.qing-hei.com/index.php/Index/Api?type=login";
    public static final String topup_record = "http://api.qing-hei.com/index.php/Index/Api?type=topup_record";
    public static final String mine = "http://api.qing-hei.com/index.php/Index/Api?type=mine";
    public static final String sex_update = "http://api.qing-hei.com/index.php/Index/Api?type=sex_update";
    public static final String nickname_update = "http://api.qing-hei.com/index.php/Index/Api?type=nickname_update";
    public static final String phone_update = "http://api.qing-hei.com/index.php/Index/Api?type=phone_update";
    public static final String train_update = "http://api.qing-hei.com/index.php/Index/Api?type=train_update";
    public static final String pwd_update = "http://api.qing-hei.com/index.php/Index/Api?type=pwd_update";
    public static final String exit = "http://api.qing-hei.com/index.php/Index/Api?type=exit";
    public static final String blackcardnew = "http://api.qing-hei.com/index.php/Index/Api?type=blackcardnew";
    public final static String haowuorder = "http://api.qing-hei.com/index.php/Index/Api?type=haowuorder";
    public final static String guanjiaorder = "http://api.qing-hei.com/index.php/Index/Api?type=guanjiaorder";
    public final static String haowuorderdetail = "http://api.qing-hei.com/index.php/Index/Api?type=haowuorderdetail";
    public final static String delhaowuorder = "http://api.qing-hei.com/index.php/Index/Api?type=delhaowuorder";
    public final static String guanjiaorderdetail = "http://api.qing-hei.com/index.php/Index/Api?type=guanjiaorderdetail";
    public final static String delguanjiaorder = "http://api.qing-hei.com/index.php/Index/Api?type=delguanjiaorder";
    public final static String myCoffeeOrder = "http://api.qing-hei.com/index.php/Index/Api?type=myCoffeeOrder";
    public final static String updateCOrder = "http://api.qing-hei.com/index.php/Index/Api?type=updateCOrder";
    public final static String getPayCode = "http://api.qing-hei.com/index.php/Index/Api?type=getPayCode";
    public final static String head_update = "http://api.qing-hei.com/index.php/Index/Api?type=head_update";
    public final static String delCoffeeOrder = "http://api.qing-hei.com/index.php/Index/Api?type=delCoffeeOrder";
    public final static String queryKd = "http://api.qing-hei.com/index.php/Index/Api?type=queryKd";
    public final static String getUserBlackkey = "http://api.qing-hei.com/index.php/Index/Api?type=getUserBlackkey";
    public final static String getBlackkey = "http://api.qing-hei.com/index.php/Index/Api?type=getBlackkey";
    public final static String reward = "http://api.qing-hei.com/index.php/Index/Api?type=reward";
    public final static String complain = "http://api.qing-hei.com/index.php/Index/Api?type=complain";
    public final static String complaintlist = "http://api.qing-hei.com/index.php/Index/Api?type=complaintlist";
    public final static String tag = "http://api.qing-hei.com/index.php/Index/Api?type=tag";
    public final static String update_openid = "http://api.qing-hei.com/index.php/Index/Api?type=update_openid";
    public final static String imresetpwd = "http://api.qing-hei.com/index.php/Index/Api?type=imresetpwd";
    public final static String pushtoken_update = "http://api.qing-hei.com/index.php/Index/Api?type=pushtoken_update";
    public final static String levelUp = "http://api.qing-hei.com/index.php/Index/Api?type=levelUp";
    public final static String levelUpOrder = "http://api.qing-hei.com/index.php/Index/Api?type=levelUpOrder";
    public final static String getPayData = "http://api.qing-hei.com/index.php/Index/Api?type=getPayData";
    public final static String signIn = "http://api.qing-hei.com/index.php/Index/Api?type=signIn";
    public final static String doSignIn = "http://api.qing-hei.com/index.php/Index/Api?type=doSignIn";
    public final static String myDriverOrder = "http://api.qing-hei.com/index.php/Index/Api?type=myDriverOrder";
    public final static String delDriverOrder = "http://api.qing-hei.com/index.php/Index/Api?type=delDriverOrder";
    public final static String getUerBonus = "http://api.qing-hei.com/index.php/Index/Api?type=getUerBonus";
    public final static String myDriverOrderDetail = "http://api.qing-hei.com/index.php/Index/Api?type=myDriverOrderDetail";
    public final static String getMyBonus = "http://api.qing-hei.com/index.php/Index/Api?type=getMyBonus";
    public final static String welfareCate = "http://api.qing-hei.com/index.php/Index/Api?type=welfareCate";
    public final static String myShare = "http://api.qing-hei.com/index.php/Index/Api?type=myShare";
    public final static String myInvite = "http://api.qing-hei.com/index.php/Index/Api?type=myInvite";
    public final static String inviteChange = "http://api.qing-hei.com/index.php/Index/Api?type=inviteChange";
    public final static String getDefaultAddress = "http://api.qing-hei.com/index.php/Index/Api?type=getDefaultAddress";
    public final static String myTask = "http://api.qing-hei.com/index.php/Index/Api?type=myTask";

}
